### ISSUE TITLE
Global variable leak

### ISSUE THREAD

**Issue by manubb** [GerHobbelt/jison#5]
Hello.
It seems that variable stack_pointer used [here](https://github.com/GerHobbelt/jison/blob/master/lib/jison.js#L5331) is not defined and hence leaks on window.
Regards,
Manuel

**Comment by GerHobbelt** [comment]
Good catch! Thanks!

Should be fixed in the next tagged build which should show up in about an hour from now (if the build+tag scripts deliver, that is :wink: )

**Comment by GerHobbelt** [comment]
fixed in version: 0.4.18-172
