### ISSUE TITLE
Creating multiple, independent lexers

### ISSUE THREAD

**Issue by nwhetsell** [GerHobbelt/jison#9]
I’m using Jison (technically Jison Lex independently) to create a [source code preprocessor](https://github.com/nwhetsell/linter-csound/blob/e27f8bed8bd117310bb8df4d9fc160016fe71e07/lib/csound-parser/preprocessor.jisonlex): the lexer is the preprocessor. Something I need to do is expand macros. The expanded macros can contain more macros that need to be expanded, so I must do this recursively by creating multiple preprocessors. Because Jison Lex generates a lexer as an object (and not, say, a function that can be instantiated with `new`), I need to create multiple preprocessors in a hacky way in Node.js. First, I delete the lexer from the [Node.js module cache](https://nodejs.org/api/modules.html#modules_caching), and then I `require` the lexer file again. (I’m doing this [here](https://github.com/nwhetsell/linter-csound/blob/e27f8bed8bd117310bb8df4d9fc160016fe71e07/lib/csound-parser/preprocessor.jisonlex#L1039-L1040).) If I didn’t do this, a child preprocessor handling an expanded macro would be the same object as the parent preprocessor that expanded the macro.

Unfortunately, this Node.js hack no longer seems to work in [Atom](https://atom.io) v1.17. There’s some kind of additional module caching happening that I can’t circumvent.

My question is: is there a way to set up Jison so that multiple, independent lexers can be used? I’ve tried doing this with Jison Lex alone and by using `new Parser()` in Jison, but everything seems to use the same lexer object.

**Comment by GerHobbelt** [comment]
A good answer to this is pending...

I *think* one can do a C-style preprocessor without the need for recursive lexing (which comes across as 'abusing' the lexer as a *parser*, but that's possibly a pedantic stance to some :wink: ) and construct a C-style preprocessor (which' language isn't a great fit for tokenized LR anayway) using possibly an *iterative* approach, using a lexer and a (maybe custom) parser.

Anyway, my main concern with recursion, hence nested invocation, of the lexer is that I have run into JavaScript stack blow-out situations in similar circumstances, i.e. in more or less deep recursive call chains of functions which are relatively stackspace heavy.

Translated: a recursive approach would limit macro depth and/or other parts of the preprocessor language behaviour which are handled in a recursive fashion and overflowing such a limit would be both machine dependent (mobile vs desktop vs server/Node) and fatal (exception thrown, which can be caught, but one should wonder: is an exception really the way to go in this situation?)

The iterative approach I'm thinking about wouldn't suffer from this 'limited depth' problem, at least not in any but **extremely** pathological circumstances: when done correctly, the only way to make such an implementation bomb out would be by feeding it a very large specially crafted input to lex&parse.

**Comment by nwhetsell** [comment]
I agree 100%. For what it’s worth, in my _particular_ case, I’m trying to make my Jison Lex lexer look at least somewhat like a pre-existing Flex lexer that uses `yy_scan_string` to do macro expansion. (I’m limiting macro depth to avoid overflowing the stack.)

**Comment by GerHobbelt** [comment]
You can do this (have multiple lexer **clones/duplicates** at run-time) as shown in the code below (see also commit SHA-1: 62e6ea4cc135723e9f9d240a7ae2d89a106a74bb :: add tests to showcase two possible solutions for https://github.com/GerHobbelt/jison/issues/9).

This is at least possible since [the latest 0.6.1-200 jison-gho release](https://www.npmjs.com/package/jison-gho) as we publish the lexer generator API, etc. via the Jison API as well (vanilla Jison doesn't do that, at least not this extensively.)

The two approaches are quite different in effect:

- the first one simple **re-generates the entire lexer from its grammar specification**. In other words: you run the lexer generator **twice** if you want to have 2 lexer instances. This is only really useful when you have multiple lexer grammars to process in the same run-time as every generated lexer takes time and space.

- the second approach is a little trick copied from the parser generator run-time: we create a *constructor function* (which makes sure that the `yy` is bound to the instance, rather than the prototype), which is then assigned an already previously created lexer as a prototype. That way you can **instantiate multiple independent instances of the same lexer**. Here the trick is to invoke the lexer API `setInput()` on each of these instances to ensure that you have independent lexers working on different (independent) input streams.

The test code which showcases both approaches:

```
describe("Github issues", function () {
  // related to https://github.com/GerHobbelt/jison/issues/9
  //
  // We explicitly obtain the Jison Lexer generator API from the 
  // Jison API (which acts as a 'facade' there):
  var RegExpLexer = Jison.Lexer;

  //
  // NOTE:
  // 
  // Compare these tests with the ones in packages/jison-lex/: 
  // you'll find they are identical, since we use exactly the same
  // API here, only now obtained via Jison itself.
  // 
  it("GerHobbelt/jison#9:: test multiple independent lexer instances", function() {
    var dict1 = {
        rules: [
           ["x", "return 'X';" ],
           ["y", "return 'Y';" ],
           ["$", "return 'EOF';" ]
       ]
    };

    var dict2 = {
        rules: [
           ["a", "return 'A';" ],
           ["b", "return 'B';" ],
           ["$", "return 'EOF';" ]
       ]
    };

    var input1 = "xxyx";
    var input2 = "aaba";

    var lexer1 = new RegExpLexer(dict1, input1);
    var lexer2 = new RegExpLexer(dict2, input2);
    assert.equal(lexer1.lex(), "X");
    assert.equal(lexer2.lex(), "A");
    assert.equal(lexer1.lex(), "X");
    assert.equal(lexer2.lex(), "A");
    assert.equal(lexer1.lex(), "Y");
    assert.equal(lexer2.lex(), "B");
    assert.equal(lexer1.lex(), "X");
    assert.equal(lexer2.lex(), "A");
    assert.equal(lexer1.lex(), "EOF");
    assert.equal(lexer2.lex(), "EOF");
  });

  it("GerHobbelt/jison#9:: test cloned yet independent lexer instances", function() {
    var dict = {
        rules: [
           ["x", "return 'X';" ],
           ["y", "return 'Y';" ],
           ["$", "return 'EOF';" ]
       ]
    };

    var input1 = "xxyx";
    var input2 = "yyx";

    var lexerBase = new RegExpLexer(dict /*, input1 */);
    function MyLexerClass() {
        this.yy = {};
    }
    MyLexerClass.prototype = lexerBase;

    function mkLexer() {
        return new MyLexerClass();
    }

    var lexer1 = mkLexer();
    lexer1.setInput(input1, {
      one: true
    });

    var lexer2 = mkLexer();
    lexer2.setInput(input2, {
      two: true
    });

    assert.equal(lexer1.lex(), "X");
    assert.equal(lexer2.lex(), "Y");
    assert.equal(lexer1.lex(), "X");
    assert.equal(lexer2.lex(), "Y");
    assert.equal(lexer1.lex(), "Y");
    assert.equal(lexer2.lex(), "X");
    assert.equal(lexer1.lex(), "X");
    assert.equal(lexer2.lex(), "EOF");
    assert.equal(lexer1.lex(), "EOF");
    // once you've gone 'past' EOF, you get the EOF **ID** returned, rather than your custom EOF token.
    // 
    // The `EOF` attribute is just a handy constant defined in the lexer prototype...
    assert.equal(lexer2.lex(), lexerBase.EOF);
    assert.equal(lexer1.lex(), lexerBase.EOF);
    assert.equal(lexer1.EOF, lexerBase.EOF);
    assert.equal(lexer2.EOF, lexerBase.EOF);
  });
});
```

**Comment by nwhetsell** [comment]
Excellent, many thanks!
